export const programOptions = [
  'BS Information Technology (BSIT)',
  'BS Computer Science (BSCS)',
  'BS Information Systems (BSIS)',
  'BS Computer Engineering (BSCpE)',
  'BS Accountancy (BSA)',
  'BS Business Administration',
  'BS Marketing Management',
  'BS Financial Management',
  'BS Human Resource Development',
  'BS Operations Management',
  'BS Entrepreneurship',
  'BS Tourism Management',
  'BS Real Estate Management',
  'BS Civil Engineering',
  'BS Mechanical Engineering',
  'BS Electrical Engineering',
  'BS Electronics Engineering',
  'BS Industrial Engineering',
  'BS Chemical Engineering',
  'BS Aeronautical Engineering',
  'BS Agricultural Engineering',
  'BS Petroleum Engineering',
  'BS Geodetic Engineering',
  'BS Nursing',
  'BS Medical Technology',
  'BS Pharmacy',
  'BS Physical Therapy',
  'BS Occupational Therapy',
  'BS Radiologic Technology',
  'BS Respiratory Therapy',
  'BS Midwifery',
  'BS Speech-Language Pathology',
  'Bachelor in Elementary Education (BEED)',
  'Bachelor in Secondary Education (BSED)',
  'BSED Major in English',
  'BSED Major in Mathematics',
  'BSED Major in Filipino',
  'BSED Major in Biological Sciences',
  'BSED Major in Social Studies',
  'Bachelor of Physical Education',
  'Bachelor of Sports Science',
  'AB Psychology',
  'BS Psychology',
  'AB Political Science',
  'AB Philosophy',
  'AB History',
  'AB Sociology',
  'AB Anthropology',
  'AB English',
  'AB Literature',
  'AB Journalism',
  'AB Communication',
  'BS Biology',
  'BS Chemistry',
  'BS Physics',
  'BS Applied Physics',
  'BS Mathematics',
  'BS Applied Mathematics',
  'BS Statistics',
  'BS Environmental Science',
  'BS Architecture',
  'BS Interior Design',
  'Bachelor in Landscape Architecture',
  'BS Hotel and Restaurant Management',
  'BS Criminology',
  'BS Forensic Science',
  'BS Public Safety',
  'BS Agriculture',
  'BS Agribusiness',
  'BS Forestry',
  'BS Fisheries',
  'BS Agroforestry',
];

export const vocationalProgramOptions = [
  '2D Digital Animation NC III',
  '2D Game Art Development NC III',
  '3D Animation NC III',
  '3D Game Art Development NC III',
  'Animation NC II',
  'Computer Hardware Servicing NC II',
  'Programming NC IV',
  'Visual Graphic Design NC III',
  'CAD/CAM Operation NC III',
  'Technical Drafting NC II',
  'Contact Center Services NC II',
  'Customer Services NC II',
  'Medical Transcription NC II',
  'Bookkeeping NC III',
  'Automotive Servicing NC I',
  'Automotive Servicing NC II',
  'Automotive Servicing NC III',
  'Automotive Servicing NC IV',
  'Automotive Body Repairing NC II',
  'Automotive Body Painting Finishing NC I',
  'Automotive Body Painting Finishing NC II',
  'Automotive Body Painting Finishing NC III',
  'Automotive Electrical Assembly NC II',
  'Automotive Electrical Assembly NC III',
  'Automotive Mechanical Assembly NC II',
  'Automotive Mechanical Assembly NC III',
  'Auto Engine Rebuilding NC II',
  'Motorcycle/Small Engine Servicing NC II',
  'Tinsmithing (Automotive Production) NC II',
  'Electrical Installation and Maintenance NC II',
  'Electrical Installation and Maintenance NC III',
  'Electrical Installation and Maintenance NC IV',
  'Consumer Electronics Servicing NC II',
  'Consumer Electronics Servicing NC III',
  'Consumer Electronics Servicing NC IV',
  'Instrumentation and Control Servicing NC II',
  'Instrumentation and Control Servicing NC III',
  'Instrumentation and Control Servicing NC IV',
  'Mechatronics Servicing NC II',
  'Mechatronics Servicing NC III',
  'Mechatronics Servicing NC IV',
  'Shielded Metal Arc Welding (SMAW) NC I',
  'Shielded Metal Arc Welding (SMAW) NC II',
  'Shielded Metal Arc Welding (SMAW) NC III',
  'Shielded Metal Arc Welding (SMAW) NC IV',
  'Gas Metal Arc Welding (GMAW) NC I',
  'Gas Metal Arc Welding (GMAW) NC II',
  'Gas Metal Arc Welding (GMAW) NC III',
  'Gas Tungsten Arc Welding (GTAW) NC II',
  'Gas Tungsten Arc Welding (GTAW) NC IV',
  'Flux Cored Arc Welding (FCAW) NC I',
  'Flux Cored Arc Welding (FCAW) NC II',
  'Flux Cored Arc Welding (FCAW) NC III',
  'Submerged Arc Welding (SAW) NC I',
  'Submerged Arc Welding (SAW) NC II',
  'Gas Welding NC I',
  'Gas Welding NC II',
  'Carpentry NC II',
  'Carpentry NC III',
  'Masonry NC I',
  'Masonry NC II',
  'Plumbing NC I',
  'Plumbing NC II',
  'Plumbing NC III',
  'Tile Setting NC II',
  'Pipefitting NC II',
  'Scaffold Erection NC II',
  'Reinforced Steel Bar Installation NC II',
  'Formworks Installation NC II',
  'Structural Erection NC II',
  'Construction Painting NC II',
  'Construction Painting NC III',
  'Refrigeration and Air Conditioning Servicing NC I',
  'Refrigeration and Air Conditioning Servicing NC II',
  'Refrigeration and Air Conditioning Servicing NC III',
  'Air Duct Servicing NC II',
  'Ice Plant Refrigeration Servicing NC III',
  'Transport Refrigeration and Air Conditioning Servicing NC II',
  'Forklift Operation NC II',
  'Backhoe Loader NC II',
  'Bulldozer NC II',
  'Hydraulic Excavator NC II',
  'Wheel Loader NC II',
  'Motor Grader NC II',
  'Road Roller Compactor NC II',
  'Tower Crane NC II',
  'Truck Mounted Crane NC II',
  'Transit Mixer NC II',
  'Housekeeping NC II',
  'Housekeeping NC III',
  'Housekeeping NC IV',
  'Front Office Services NC II',
  'Tourism Promotion Services NC II',
  'Tour Guiding Services NC II',
  'Travel Services NC II',
  'Events Management Services NC III',
  'Attractions and Theme Parks Operation NC II',
  'Cookery NC II',
  'Commercial Cooking NC II',
  'Commercial Cooking NC III',
  'Commercial Cooking NC IV',
  'Bread and Pastry Production NC II',
  'Food and Beverage Services NC II',
  'Food and Beverage Services NC III',
  'Food and Beverage Services NC IV',
  'Bartending NC II',
  'Food Processing NC II',
  'Food Processing NC III',
  'Food Processing NC IV',
  'Caregiving NC II',
  'Barangay Health Services NC II',
  'Emergency Medical Services NC II',
  'Hilot Wellness Massage NC II',
  'Massage Therapy NC II',
  'Pharmacy Services NC II',
  'Biomedical Equipment Services NC II',
  'Dental Hygiene NC IV',
  'Ophthalmic Lens Services NC II',
  'Beauty Care NC II',
  'Beauty Care NC III',
  'Hairdressing with Cosmetology NC II',
  'Barbering NC II',
  'Dressmaking NC II',
  'Tailoring NC II',
  'Fashion Design Apparel NC III',
  'Footwear Making NC II',
  'Illustration NC II',
  'Photography NC II',
  'Performing Arts Ballroom Dancing NC II',
  'Performing Arts Dance NC II',
  'Performing Arts Song NC II',
  'Agricultural Crops Production NC I',
  'Agricultural Crops Production NC III',
  'Animal Production NC II',
  'Animal Health Care and Management NC III',
  'Horticulture NC II',
  'Horticulture NC III',
  'Organic Agriculture Production NC II',
  'Pest Management NC II',
  'Slaughtering Operations NC II',
  'Aquaculture NC II',
  'Fish Capture NC I',
  'Fish Capture NC II',
  'Fish Products Packaging NC II',
  'Driving NC II',
  'Driving NC III',
  'Driving (Articulated Vehicle) NC III',
  'Driving (Passenger Bus/Straight Truck) NC III',
  'Able Seafarer Deck',
  'Able Seafarer Engine',
  'Marine Electricity NC II',
  'English',
  'Japanese',
  'Korean',
  'Mandarin',
  'Arabic',
  'Spanish',
  'TESDA Trainer Qualification Level I',
  'TESDA Trainer Qualification Level II',
];

export const heiSchoolNames = [
  "Abra State Institute of Science and Technology-Bangued",
  "Abra State Institute of Science and Technology-Main",
  "Abuyog Community College",
  "Agusan Del Sur State College of Agriculture and Technology",
  "Agusan del Sur State College of Agriculture and Technology - Trento Campus",
  "Aklan State University-Banga Campus",
  "Aklan State University-Ibajay Campus",
  "Aklan State University-Kalibo Campus",
  "Aklan State University-Makato",
  "Aklan State University-New Washington",
  "Altavas College",
  "Antipolo Institute of Technology (AITECH)",
  "Apayao State College-Luna",
  "Apayao State College-Main",
  "Aroroy Municipal College",
  "Aurora State College of Technology",
  "Aurora State College of Technology-Bazal",
  "Aurora State College of Techonolgy-Casiguran",
  "Baao Community College",
  "Bacacay Community College",
  "Baco Community College",
  "Bacolod City College",
  "Bago City College",
  "Balete Community College",
  "Balian Community College",
  "Baliwag Polytechnic College",
  "Balud Municipal College",
  "Basilan State College",
  "Bataan Peninsula State University",
  "Bataan Peninsula State University-Abucay",
  "Bataan Peninsula State University-Bagac",
  "Bataan Peninsula State University-Balanga",
  "Bataan Peninsula State University-Dinalupihan",
  "Bataan Peninsula State University-Orani",
  "Batan Integrated College of Technology",
  "Batanes State College",
  "Batangas State University-Alangilan",
  "Batangas State University-Balayan",
  "Batangas State University-Lemery",
  "Batangas State University-Lipa City",
  "Batangas State University-Lobo",
  "Batangas State University-Mabini",
  "Batangas State University-Main",
  "Batangas State University-Malvar",
  "Batangas State University-Nasugbu",
  "Batangas State University-Rosario",
  "Batangas State University-San Juan",
  "Bayambang Polytechnic College",
  "Benguet State University-Bokod Campus",
  "Benguet State University-Buguias Campus",
  "Benguet State University-Main",
  "Benguet State University-Open University",
  "Bicol State College of Applied Sciences and Technology",
  "Bicol University Gubat Campus",
  "Bicol University-College of Agriculture and Forestry",
  "Bicol University-Daraga Campus",
  "Bicol University-Main",
  "Bicol University-Polangui Campus",
  "Bicol University-Tabaco Campus",
  "Biliran Province State University-Biliran Campus",
  "Biliran Province State University-Main",
  "Binalatongan Community College",
  "Bohol Island State University - Bilar",
  "Bohol Island State University - Calape Polytechnic College",
  "Bohol Island State University - Candijay",
  "Bohol Island State University - Clarin",
  "Bohol Island State University - Tagbilaran",
  "Bohol Island State University-Balilihan Campus",
  "Buenavista Community College",
  "Bukidnon State University",
  "Bukidnon State University - Lantapan",
  "Bukidnon State University-Alubijid ESC",
  "Bukidnon State University-Baungon BSU",
  "Bukidnon State University-Cabanglasan ESC",
  "Bukidnon State University-Damulog Satellite ESC",
  "Bukidnon State University-Impasugong",
  "Bukidnon State University-Kadingilan",
  "Bukidnon State University-Kalilangan BSU",
  "Bukidnon State University-Kitaotao Satellite ESC",
  "Bukidnon State University-Libona",
  "Bukidnon State University-Malitbog",
  "Bukidnon State University-Medina ESC",
  "Bukidnon State University-Quezon Satellite ESC",
  "Bukidnon State University-San Fernando Satellite ESC",
  "Bukidnon State University-Talakag BSU",
  "Bukidnon State University-Talisayan ESC",
  "Bulacan Agricultural State College",
  "Bulacan Agricultural State College-Do\u00f1a Remedios Trinidad",
  "Bulacan Polytechnic College",
  "Bulacan State University-Bustos",
  "Bulacan State University-Hagonoy",
  "Bulacan State University-Main",
  "Bulacan State University-Meneses",
  "Bulacan State University-San Jose Del Monte",
  "Bulacan State University-San Rafael Campus",
  "Burauen Community College",
  "Cagayan State University-Andrews",
  "Cagayan State University-Aparri",
  "Cagayan State University-Gonzaga",
  "Cagayan State University-Lallo",
  "Cagayan State University-Lasam",
  "Cagayan State University-Piat",
  "Cagayan State University-Sanchez Mira",
  "Cagayan State University-Tuguegarao (Carig)",
  "Calabanga Community College",
  "Calaca City Global College",
  "Camarines Norte State College-Aba\u00f1o Campus",
  "Camarines Norte State College-Entienza Campus",
  "Camarines Norte State College-Labo Campus",
  "Camarines Norte State College-Main",
  "Camarines Norte State College-Mercedes Campus",
  "Camarines Norte State College-Panganiban Campus",
  "Camarines Sur Polytechnic Colleges",
  "Camarines Sur Polytechnic Colleges-Buhi Campus",
  "Camiguin Polytechnic State College",
  "Capiz State University-Burias Campus",
  "Capiz State University-Dayao",
  "Capiz State University-Dumarao Campus",
  "Capiz State University-Main",
  "Capiz State University-Pilar Campus",
  "Capiz State University-Poblacion Mambusao",
  "Capiz State University-Pontevedra Campus",
  "Capiz State University-Sigma Campus",
  "Capiz State University-Tapaz Campus",
  "Caraga State University-Cabadbaran Campus",
  "Caraga State University-Main Campus",
  "Caramoan Community College",
  "Carcar City College",
  "Carlos Hilado Memorial State Universit -College of Fisheries-Binalbagan",
  "Carlos Hilado Memorial State University-Alijis",
  "Carlos Hilado Memorial State University-Bacolod Campus",
  "Carlos Hilado Memorial State University-Main",
  "Carmen Municipal College",
  "Castilla Colleges",
  "Cataingan Municipal College",
  "Catanduanes State University-Main",
  "Catanduanes State University-Panganiban",
  "Cavite State University-Bacoor City Campus",
  "Cavite State University-Carmona Campus",
  "Cavite State University-Cavite City Campus",
  "Cavite State University-General Trias Campus",
  "Cavite State University-Imus Campus",
  "Cavite State University-Main",
  "Cavite State University-Naic Campus",
  "Cavite State University-Rosario Campus",
  "Cavite State University-Silang Campus",
  "Cavite State University-Tanza Campus",
  "Cavite State University-Trece Martires City Campus",
  "Cawayan Community College",
  "Cebu Normal University",
  "Cebu Normal University - Balamban",
  "Cebu Normal University - Medellin",
  "Cebu Technological University - Cebu City Mountain Satellite Campus",
  "Cebu Technological University - College of Fisheries Technology - Carmen",
  "Cebu Technological University - Consolacion",
  "Cebu Technological University - Main",
  "Cebu Technological University-Argao Campus",
  "Cebu Technological University-Barili Campus",
  "Cebu Technological University-Daanbantayan Campus",
  "Cebu Technological University-Danao City Campus",
  "Cebu Technological University-Moalboal Campus",
  "Cebu Technological University-Pinamungajan Campus",
  "Cebu Technological University-San Francisco Campus",
  "Cebu Technological University-Tuburan Campus",
  "Central Bicol State University of Agriculture-Calabanga",
  "Central Bicol State University of Agriculture-Main",
  "Central Bicol State University of Agriculture-Pasacao",
  "Central Bicol State University of Agriculture-Sipocot",
  "Central Luzon State University",
  "Central Mindanao University",
  "Central Philippines State University - San Carlos Campus",
  "Central Philippines State University - Victorias City Campus",
  "Central Philippines State University-Candoni",
  "Central Philippines State University-Cauayan Campus",
  "Central Philippines State University-Hinigaran Campus",
  "Central Philippines State University-Hinoba-an Campus",
  "Central Philippines State University-Ilog Campus",
  "Central Philippines State University-Main Campus",
  "Central Philippines State University-Moises Padilla Campus",
  "Central Philippines State University-Sipalay Campus",
  "City College of Angeles",
  "City College of Bayawan",
  "City College of Cagayan de Oro",
  "City College of Calamba",
  "City College of Calapan",
  "City College of Davao",
  "City College of El Salvador",
  "City College of Naga",
  "City College of Ormoc",
  "City College of San Fernando",
  "City College of San Jose del Monte",
  "City College of Tagaytay",
  "City of Malabon University",
  "City University of Pasay",
  "Colegio de General Luna",
  "Colegio de Getafe",
  "Colegio de Kapatagan",
  "Colegio De La Castellana",
  "Colegio de La Ciudad de Tayabas",
  "Colegio de La Ciudad de Zamboanga",
  "Colegio De Las Navas",
  "Colegio de Loboc",
  "Colegio de Masinloc",
  "Colegio de Montalban",
  "Colegio de Muntinlupa",
  "Colegio de Nabunturan",
  "Colegio de Naujan",
  "Colegio de Puerto Galera",
  "Colegio De San Leonardo",
  "Colegio ng Lungsod ng Batangas",
  "Community College of Gingoog City",
  "Community College of Manito",
  "Cordova Public College",
  "Cotabato Foundation College of Science and Technology",
  "Cotabato Foundation College of Science and Technology-Antipas Campus",
  "Cotabato Foundation College of Science and Technology-Katipunan Campus",
  "Cotabato Foundation College of Science and Technology-Pikit Campus",
  "Dalubhasaan ng Lungsod ng Lucena",
  "Dalubhasaan ng Lungsod ng San Pablo",
  "Danao Techological College",
  "Daraga Community College",
  "Davao De Oro State College",
  "Davao De Oro State College-Maragusan Branch",
  "Davao De Oro State College-Montevista Branch",
  "Davao De Oro State College-New Bataan Branch",
  "Davao del Norte State College",
  "Davao del Sur State College-Main",
  "Davao Oriental State University",
  "Davao Oriental State University-Banaybanay Campus",
  "Davao Oriental State University-Cateel Extension Campus",
  "Davao Oriental State University-San Isidro Campus",
  "Development Academy of the Philippines",
  "Dingalan Community College",
  "Don Carlos Polytechnic College",
  "Don Honorio Ventura State University - Apalit",
  "Don Honorio Ventura State University - Candaba",
  "Don Honorio Ventura State University - Lubao",
  "Don Honorio Ventura State University - Main",
  "Don Honorio Ventura State University - Mexico",
  "Don Honorio Ventura State University - Porac",
  "Don Honorio Ventura State University - Sto. Tomas",
  "Don Mariano Marcos Memorial State University-Mid La Union",
  "Don Mariano Marcos Memorial State University-North La Union-Main Campus",
  "Don Mariano Marcos Memorial State University-Open University",
  "Don Mariano Marcos Memorial State University-South La Union",
  "Donsol Community College",
  "Dr. Emilio B. Espinosa Sr. Memorial State College of Agriculture and Technology",
  "Dr. Emilio B. Espinosa Sr. Memorial State College of Agriculture and Technology-Cawayan Campus",
  "Dr. Filemon C. Aguilar Memorial College of Las Pi\u00f1as",
  "Dr. Jose Fabella Memorial Hospital School of Midwifery",
  "Eastern Samar State University",
  "Eastern Samar State University-Can-Avid Campus",
  "Eastern Samar State University-Guiuan Campus",
  "Eastern Samar State University-Maydolong Campus",
  "Eastern Samar State University-Salcedo Campus",
  "Eastern Visayas State University",
  "Eastern Visayas State University-Burauen Campus",
  "Eastern Visayas State University-Carigara Campus",
  "Eastern Visayas State University-Dulag Campus",
  "Eastern Visayas State University-Ormoc Campus",
  "Eastern Visayas State University-Tanauan Campus",
  "Eduardo L. Joson Memorial College",
  "Eulogio \"Amang\" Rodriguez Institute of Science and Technology",
  "Eulogio \"Amang\" Rodriguez Institute of Science and Technology-Cavite",
  "Gapan City College",
  "Glan Institute of Technology",
  "Goa Community College",
  "Gordon College",
  "Gov. Alfonso D. Tan College",
  "Governor Generoso College of Arts Sciences and Technology",
  "Governor Mariano E. Villafuerte Community College-Garchitorena",
  "Governor Mariano E. Villafuerte Community College-Libmanan",
  "Governor Mariano E. Villafuerte Community College-Siruma",
  "Governor Mariano E. Villafuerte Community College-Tinambac",
  "Guagua Community College",
  "Guimaras State College-Baterna Campus",
  "Guimaras State College-Main",
  "Guimaras State College-Mosqueda",
  "Hinatuan Southern College",
  "Ifugao State University - Lagawe Campus",
  "Ifugao State University - Main",
  "Ifugao State University - Potia",
  "Ifugao State University - Tinoc",
  "Ifugao State University-Aguinaldo",
  "Ifugao State University-Hapao",
  "Ilocos Sur Community College",
  "Ilocos Sur Polytechnic State College-Candon",
  "Ilocos Sur Polytechnic State College-Cervantes",
  "Ilocos Sur Polytechnic State College-College of Arts and Sciences-Tagudin",
  "Ilocos Sur Polytechnic State College-College of Engineering and Technology-Santiago",
  "Ilocos Sur Polytechnic State College-College of Fisheries and Marine Sciences-Narvacan",
  "Ilocos Sur Polytechnic State College-Main Campus",
  "Ilocos Sur Polytechnic State College-Sta. Maria",
  "Iloilo City Community College",
  "Iloilo Science and Technology University-Barotac Nuevo Campus",
  "Iloilo Science and Technology University-Dumangas Campus",
  "Iloilo Science and Technology University-Leon Campus",
  "Iloilo Science and Technology University-Main",
  "Iloilo Science and Technology University-Miagao Campus",
  "Iloilo State College of Fisheries-Barotac Nuevo Campus",
  "Iloilo State College of Fisheries-Dingle Campus",
  "Iloilo State college of Fisheries-Dumangas Campus",
  "Iloilo State College of Fisheries-Main",
  "Iloilo State College of Fisheries-San Enrique Campus",
  "Inabanga College of Arts and Sciences",
  "Initao College",
  "Isabela State University-Angadanan Campus",
  "Isabela State University-Cabagan",
  "Isabela State University-Cauayan Campus",
  "Isabela State University-Ilagan Campus",
  "Isabela State University-Jones Campus",
  "Isabela State University-Main (Echague)",
  "Isabela State University-Palanan Campus",
  "Isabela State University-Roxas Campus",
  "Isabela State University-San Mariano Campus",
  "Isabela State University-San Mateo Campus",
  "Jose Rizal Memorial State University - Main",
  "Jose Rizal Memorial State University-Dipolog",
  "Jose Rizal Memorial State University-Katipunan Campus",
  "Jose Rizal Memorial State University-Siocon",
  "Jose Rizal Memorial State University-Tampilisan",
  "Josefina H. Cerilles State College",
  "Josefina H. Cerilles State College - Dumingag",
  "Josefina H. Cerilles State College - Pagadian",
  "Josefina H. Cerilles State College-Canuto M.S. Enerio College of Arts and Trades",
  "Kalinga State University-Dagupan",
  "Kalinga State University-Main",
  "Kalinga State University-Rizal",
  "Kapalong College of Agriculture Sciences and Technology",
  "Kolehiyo ng Lungsod ng Dasmari\u00f1as",
  "Kolehiyo ng Lungsod ng Lipa",
  "Kolehiyo ng Pantukan",
  "Kolehiyo ng Subic",
  "La Carlota City College",
  "Laguna State Polytechnic University-Los Ba\u00f1os",
  "Laguna State Polytechnic University-Main",
  "Laguna State Polytechnic University-San Pablo City",
  "Laguna State Polytechnic University-Sta. Cruz",
  "Laguna University",
  "Lapu-lapu City College",
  "Leyte Normal University",
  "Leyte Normal University-San Isidro Campus",
  "Libon Community College",
  "Ligao Community College",
  "Limay Polytechnic College",
  "Mabalacat City College",
  "Maco de Oro College",
  "Madridejos Community College",
  "Magsaysay College",
  "Makilala Institute of Science and Technology",
  "Malapatan College of Science and Technology",
  "Malay College",
  "Mandaluyong College of Science and Technology",
  "Mandaue City College",
  "Mariano Marcos State University-College of Agriculture and Forestry-Dingras",
  "Mariano Marcos State University-College of Aquatic Sciences and Applied Technology",
  "Mariano Marcos State University-College of Industrial Technology-Laoag City",
  "Mariano Marcos State University-College of Teacher Education-Laoag City",
  "Mariano Marcos State University-Main",
  "Marikina Polytechnic College",
  "Marinduque State University-Gasan Campus",
  "Marinduque State University-Main Campus",
  "Marinduque State University-Sta. Cruz Campus",
  "Marinduque State University-Torrijos Campus",
  "Mindanao State University - Iligan Institute of Technology",
  "Mindanao State University-Buug College",
  "Mindanao State University-General Santos",
  "Mindanao State University-Lanao Del Norte Agricultural College",
  "Mindanao State University-Maigo School of Arts and Trades",
  "Mindanao State University-Naawan",
  "Mindoro State University-Bongabong Campus",
  "Mindoro State University-Calapan City Campus",
  "Mindoro State University-Main Campus",
  "Monkayo College of Arts Sciences and Technology",
  "Mountain Province State Polytechnic College-Main",
  "Mountain Province State Polytechnic College-Tadian",
  "National Defense College",
  "Navotas Polytechnic College",
  "Negros Oriental State University -Bais II",
  "Negros Oriental State University-Bais1",
  "Negros Oriental State University-Bayawan",
  "Negros Oriental State University-Guihulngan",
  "Negros Oriental State University-Mabinay Institute of Technology",
  "Negros Oriental State University-Main Campus",
  "Negros Oriental State University-Siaton Community College",
  "North Eastern Mindanao State University-Cagwait",
  "North Eastern Mindanao State University-Cantilan",
  "North Eastern Mindanao State University-Lianga",
  "North Eastern Mindanao State University-Main",
  "North Eastern Mindanao State University-San Miguel",
  "North Eastern Mindanao State University-Tagbina",
  "Northern Bukidnon State College",
  "Northern Iloilo State University-Ajuy Campus",
  "Northern Iloilo State University-Barotac Viejo Campus",
  "Northern Iloilo State University-Batad Campus",
  "Northern Iloilo State University-Concepcion Campus",
  "Northern Iloilo State University-Estancia Iloilo",
  "Northern Iloilo State University-Lemery Campus",
  "Northern Iloilo State University-Sara Campus",
  "Northern Negros State College of Science and Technology",
  "Northern Negros State College of Science and Technology-Calatrava",
  "Northern Negros State College of Science and Technology-Escalante",
  "Northwest Samar State University",
  "Northwest Samar State University-San Jorge Campus",
  "Northwestern Mindanao State College of Science and Technology",
  "Norzagaray College",
  "Nueva Ecija University of Science and Technology-Atate",
  "Nueva Ecija University of Science and Technology-Carranglan",
  "Nueva Ecija University of Science and Technology-Fort Magsaysay",
  "Nueva Ecija University of Science and Technology-Main",
  "Nueva Ecija University of Science and Technology-Papaya",
  "Nueva Ecija University of Science and Technology-Pe\u00f1aranda",
  "Nueva Ecija University of Science and Technology-San Antonio Campus",
  "Nueva Ecija University of Science and Technology-San Isidro Campus",
  "Nueva Ecija University of Science and Technology-San Leonardo",
  "Nueva Ecija University of Science and Technology-Sebani Estate Agricultural College",
  "Nueva Ecija University of Science and Technology-Sto. Domingo",
  "Nueva Ecija University of Science and Technology-Sumacab Campus",
  "Nueva Ecija University of Science and Technology-Talavera",
  "Nueva Vizcaya State University - Main Bayombong",
  "Nueva Vizcaya State University-Bambang",
  "Oas Community College",
  "Occidental Mindoro State College",
  "Occidental Mindoro State College-Labangan Campus",
  "Occidental Mindoro State College-Lubang Campus",
  "Occidental Mindoro State College-Mamburao",
  "Occidental Mindoro State College-Murtha Campus",
  "Occidental Mindoro State College-Sablayan Campus",
  "One Cainta College",
  "Opol Community College",
  "Pagadian City International College",
  "Palawan State University",
  "Palawan State University- Balabac",
  "Palawan State University- Brooke's Point",
  "Palawan State University-Araceli",
  "Palawan State University-Bataraza",
  "Palawan State University-Coron",
  "Palawan State University-Cuyo",
  "Palawan State University-Dumaran",
  "Palawan State University-Linapacan",
  "Palawan State University-Narra",
  "Palawan State University-New El Nido",
  "Palawan State University-Quezon",
  "Palawan State University-Rizal",
  "Palawan State University-Roxas",
  "Palawan State University-San Rafael Puerto Princesa City",
  "Palawan State University-San Vicente",
  "Palawan State University-Sofronio Espa\u00f1ola",
  "Palawan State University-Taytay",
  "Palompon Institute of Technology",
  "Palompon Institute of Technology-Tabango Campus",
  "Pamantasan ng Cabuyao",
  "Pamantasan ng Lungsod ng Marikina",
  "Pamantasan ng Lungsod ng Maynila",
  "Pamantasan ng Lungsod ng Muntinlupa",
  "Pamantasan ng Lungsod ng Pasig",
  "Pamantasan ng Lungsod ng Valenzuela",
  "Pambayang Dalubhasaan ng Marilao",
  "Pambayang Kolehiyo ng Mauban",
  "Pampanga State Agricultural University",
  "Pangantucan Bukidnon Community College",
  "Pangasinan Polytechnic College",
  "Pangasinan State University",
  "Pangasinan State University-Alaminos City",
  "Pangasinan State University-Asingan",
  "Pangasinan State University-Bayambang",
  "Pangasinan State University-Binmaley",
  "Pangasinan State University-Infanta",
  "Pangasinan State University-Open University",
  "Pangasinan State University-San Carlos City",
  "Pangasinan State University-Sta. Maria",
  "Pangasinan State University-Urdaneta City",
  "Para\u00f1aque City College",
  "Partido State University-Caramoan Campus",
  "Partido State University-Lagonoy Campus",
  "Partido State University-Main",
  "Partido State University-Sag\u00f1ay Campus",
  "Partido State University-Salogon Campus",
  "Partido State University-San Jose Campus",
  "Partido State University-Tinambac Campus",
  "Passi City College",
  "Pateros Technological College",
  "Philippine Merchant Marine Academy",
  "Philippine Military Academy",
  "Philippine National Police Academy",
  "Philippine Normal University-Cadiz",
  "Philippine Normal University-Lopez",
  "Philippine Normal University-Main",
  "Philippine Normal University-Mindanao Campus",
  "Philippine Normal University-North Luzon Campus",
  "Philippine Public Safety College",
  "Philippine State College of Aeronautics-Fernando Air Base",
  "Philippine State College of Aeronautics-Mactan Air Base",
  "Philippine State College of Aeronautics-Main",
  "Philippine State College of Aeronautics-Pampanga Extension",
  "Pilar Community College",
  "Pola Community College",
  "Polangui Community College",
  "Polytechnic College of Botolan",
  "Polytechnic College of the City of Meycauayan",
  "Polytechnic University of the Philippines",
  "Polytechnic University of the Philippines-Alfonso",
  "Polytechnic University of the Philippines-Bansud",
  "Polytechnic University of the Philippines-Bi\u00f1an",
  "Polytechnic University of the Philippines-Cabiao",
  "Polytechnic University of the Philippines-Calauan",
  "Polytechnic University of the Philippines-General Luna Quezon",
  "Polytechnic University of the Philippines-Lopez",
  "Polytechnic University of the Philippines-Maragondon",
  "Polytechnic University of the Philippines-Mariveles",
  "Polytechnic University of the Philippines-Mulanay",
  "Polytechnic University of the Philippines-Para\u00f1aque Campus",
  "Polytechnic University of The Philippines-Pulilan",
  "Polytechnic University of the Philippines-Quezon City Campus",
  "Polytechnic University of the Philippines-Ragay",
  "Polytechnic University of the Philippines-Sablayan",
  "Polytechnic University of the Philippines-San Juan Campus",
  "Polytechnic University of the Philippines-San Pedro",
  "Polytechnic University of the Philippines-Sta. Maria Bulacan",
  "Polytechnic University of the Philippines-Sta. Rosa",
  "Polytechnic University of the Philippines-Sto. Tomas",
  "Polytechnic University of the Philippines-Taguig",
  "Polytechnic University of the Philippines-Unisan",
  "President Ramon Magsaysay State University",
  "President Ramon Magsaysay State University-Botolan",
  "President Ramon Magsaysay State University-Candelaria",
  "President Ramon Magsaysay State University-Castillejos",
  "President Ramon Magsaysay State University-Masinloc",
  "President Ramon Magsaysay State University-San Marcelino",
  "President Ramon Magsaysay State University-Sta. Cruz",
  "Quezon City University",
  "Quirino State University",
  "Quirino State University - Cabarroguis",
  "Quirino State University - Maddela",
  "Rapu-Rapu Community College",
  "Rizal Technological University",
  "Rizal Technological University-Pasig",
  "Romblon State University-Cajidiocan Campus",
  "Romblon State University-Calatrava Campus",
  "Romblon State University-Main",
  "Romblon State University-Romblon Campus",
  "Romblon State University-San Agustin Campus",
  "Romblon State University-San Andres Campus",
  "Romblon State University-San Fernando Campus",
  "Romblon State University-San Jose Campus",
  "Romblon State University-Sta. Fe Campus",
  "Romblon State University-Sta. Maria Campus",
  "Salay Community College",
  "Samal Island City College",
  "Samar State University",
  "Samar State University-Basey Campus",
  "Samar State University-Mercedes Campus",
  "Surigao State College of Technology-Del Carmen",
  "Surigao State College of Technology-Main",
  "Surigao State College of Technology-Mainit",
  "Surigao State College of Technology-Malimono",
  "Tagbilaran City College",
  "Tagoloan Community College",
  "Taguig City University",
  "Talibon Polytechnic College",
  "Talisay City College",
  "Tanauan City College",
  "Tarlac Agricultural University",
  "Tarlac State University",
  "Technological University of the Philippines-Cavite",
  "Technological University of the Philippines-Manila",
  "Technological University of the Philippines-Taguig",
  "Technological University of the Philippines-Visayas",
  "Tiwi Community College",
  "Trece Martires City College",
  "Trinidad Municipal College",
  "Tubod College",
  "Ubay Community College",
  "Universidad de Manila",
  "University of Antique - Caluya",
  "University of Antique - Hamtic",
  "University of Antique - Libertad",
  "University of Antique - Main",
  "University of Antique - Tario Lim Antique School of Fisheries",
  "University of Caloocan City",
  "University of Eastern Pangasinan",
  "University of Eastern Philippines",
  "University of Eastern Philippines-Catubig Campus",
  "University of Eastern Philippines-Laoang Campus",
  "University of Makati",
  "University of Northern Philippines",
  "University of Rizal System-Angono",
  "University of Rizal System-Antipolo",
  "University of Rizal System-Binangonan",
  "University of Rizal System-Cainta",
  "University of Rizal System-Cardona",
  "University of Rizal System-Morong",
  "University of Rizal System-Pililia",
  "University of Rizal System-Rodriguez",
  "University of Rizal System-Tanay",
  "University of Rizal System-Taytay",
  "University of Science and Technology in Southern Philippines-Alubijid",
  "University of Science and Technology in Southern Philippines-Balubal",
  "University of Science and Technology in Southern Philippines-Villanueva",
  "University of Science and Technology of Southern Philippines",
  "University of Science and Technology of Southern Philippines - Claveria",
  "University of Science and Technology of Southern Philippines - Jasaan",
  "University of Science and Technology of Southern Philippines - Oroquieta",
  "University of Science and Technology of Southern Philippines - Panaon",
  "University of Southeastern Philippines-Bislig Campus",
  "University of Southeastern Philippines-College of Agriculture-Tagum Mabini",
  "University of Southeastern Philippines-Main",
  "University of Southeastern Philippines-Mintal",
  "University of Southern Mindanao-Kidapawan City Campus",
  "University of Southern Mindanao-Main",
  "University of the Philippines in the Visayas Tacloban College",
  "University of the Philippines Manila - School of Health Sciences",
  "University of the Philippines- Manila School of Health Sciences Extension Campus-Baler",
  "University of the Philippines- Manila School of Health Sciences Extension Campus-Tarlac",
  "University of the Philippines-Baguio",
  "University of the Philippines-College of Cebu",
  "University of the Philippines-Diliman",
  "University of the Philippines-Diliman (Olongapo City)",
  "University of the Philippines-Diliman (Pampanga)",
  "University of the Philippines-Los Ba\u00f1os",
  "University of the Philippines-Manila",
  "University of the Philippines-Mindanao",
  "University of the Philippines-Open University",
  "University of The Philippines-Visayas",
  "UPM-School of Health And Sciences - Koronadal Campus",
  "Urdaneta City University",
  "Valenzuela City Polytechnic College",
  "Vicente A. Javier Memorial Community College",
  "Visayas State University",
  "Visayas State University-Alang-Alang Campus",
  "Visayas State University-Isabel Campus",
  "Visayas State University-Tolosa Campus",
  "Visayas State University-Villaba Campus",
  "West Visayas State University-Calinog Campus",
  "West Visayas State University-College of Agriculture and Forestry Lambunao",
  "West Visayas State University-Himamaylan Campus Extension",
  "West Visayas State University-Janiuay Campus",
  "West Visayas State University-Lambunao Campus",
  "West Visayas State University-Main",
  "West Visayas State University-Pototan Campus",
  "Western Mindanao State University",
  "Western Mindanao State University-Alicia",
  "Western Mindanao State University-Curuan",
  "Western Mindanao State University-Diplahan",
  "Western Mindanao State University-Imelda",
  "Western Mindanao State University-Ipil",
  "Western Mindanao State University-Mabuhay",
  "Western Mindanao State University-Malangas",
  "Western Mindanao State University-Olutanga",
  "Western Mindanao State University-Pagadian",
  "Western Mindanao State University-Siay",
  "Western Mindanao State University-Tungawan",
  "Western Philippines University",
  "Western Philippines University-Busuanga",
  "Western Philippines University-Culion",
  "Western Philippines University-El Nido",
  "Western Philippines University-Puerto Princesa",
  "Western Philippines University-Quezon",
  "Western Philippines University-Rio Tuba",
  "Zamboanga del Sur Provincial Government College",
  "Zamboanga del Sur Provincial Government College - Pagadian",
  "Zamboanga del Sur Provincial Government College-Dimataling",
  "Zamboanga Peninsula Polytechic State University-Vitali",
  "Zamboanga Peninsula Polytechnic State University",
  "Zamboanga Peninsula Polytechnic State University-Kabasalan",
  "Zamboanga Peninsula Polytechnic State University-Malangas",
  "Zamboanga Peninsula Polytechnic State University-Siay",
  "Zamboanga State College of Marine Sciences and Technology"
];
